-- ============================================================
-- SCRIPT DE MIGRACIÓN DE ESQUEMA COMPLETO PARA PROMEDICAL
-- Ejecutar este script en el SQL Editor del nuevo proyecto Supabase:
-- https://bapismzckjpyqqmyfvdn.supabase.co
-- ============================================================

-- 1. TABLA USUARIOS
CREATE TABLE IF NOT EXISTS usuarios (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    nombre TEXT,
    correo TEXT,
    foto_url TEXT,
    password TEXT,
    rol TEXT,
    especialidad TEXT
);
ALTER TABLE usuarios DISABLE ROW LEVEL SECURITY;

-- 2. TABLA PACIENTES
CREATE TABLE IF NOT EXISTS pacientes (
    cedula TEXT PRIMARY KEY,
    nombre TEXT NOT NULL,
    edad INTEGER,
    profesion TEXT,
    seguro TEXT DEFAULT 'Particular',
    sexo CHAR(1),
    telefono TEXT,
    email TEXT,
    altura TEXT,
    peso TEXT,
    carnet_seguro TEXT,
    antecedentes_personales TEXT,
    antecedentes_familiares TEXT,
    alergias TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    fecha_nacimiento TEXT,
    foto_url TEXT,
    direccion TEXT,
    tipo_sangre TEXT
);
ALTER TABLE pacientes DISABLE ROW LEVEL SECURITY;

-- 3. TABLA SIGNOS VITALES
CREATE TABLE IF NOT EXISTS signos_vitales (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    paciente_cedula TEXT REFERENCES pacientes(cedula) ON DELETE CASCADE,
    fecha TIMESTAMPTZ DEFAULT NOW(),
    presion_arterial TEXT,
    frecuencia_cardiaca INTEGER,
    temperatura NUMERIC(4,2),
    peso NUMERIC(5,2),
    talla NUMERIC(5,2),
    imc NUMERIC(4,2),
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE signos_vitales DISABLE ROW LEVEL SECURITY;

-- 4. TABLA CITAS
CREATE TABLE IF NOT EXISTS citas (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    turno BIGINT,
    nombre TEXT NOT NULL,
    cedula TEXT NOT NULL,
    edad INTEGER,
    seguro TEXT,
    sexo CHAR(1),
    fecha DATE NOT NULL,
    estado TEXT,
    hora TEXT,
    altura TEXT,
    peso TEXT,
    profesion TEXT,
    instruccion_cobro TEXT,
    monto_cobrado NUMERIC(10,2),
    carnet_seguro TEXT,
    telefono TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    fecha_nacimiento TEXT
);
ALTER TABLE citas DISABLE ROW LEVEL SECURITY;

-- 5. TABLA CONSULTAS
CREATE TABLE IF NOT EXISTS consultas (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    paciente_cedula TEXT REFERENCES pacientes(cedula) ON DELETE CASCADE,
    fecha DATE NOT NULL,
    diagnostico TEXT,
    receta TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE consultas DISABLE ROW LEVEL SECURITY;

-- 6. TABLA TRANSACCIONES
CREATE TABLE IF NOT EXISTS transacciones (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fecha DATE DEFAULT CURRENT_DATE,
    concepto TEXT NOT NULL,
    categoria TEXT,
    monto NUMERIC(15,2) NOT NULL,
    paciente TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE transacciones DISABLE ROW LEVEL SECURITY;

-- 7. TABLA FACTURAS SEGURO
CREATE TABLE IF NOT EXISTS facturas_seguro (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cedula TEXT NOT NULL,
    nombre_paciente TEXT NOT NULL,
    edad INTEGER,
    carnet_seguro TEXT,
    seguro TEXT NOT NULL,
    fecha DATE DEFAULT CURRENT_DATE,
    monto NUMERIC(15,2) NOT NULL,
    estado TEXT DEFAULT 'pendiente',
    fecha_pago DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE facturas_seguro DISABLE ROW LEVEL SECURITY;

-- 8. TABLA CONFIGURACION DOCTOR
CREATE TABLE IF NOT EXISTS configuracion_doctor (
    id INTEGER PRIMARY KEY DEFAULT 1,
    nombre_doctor TEXT NOT NULL,
    especialidad TEXT,
    foto_url TEXT,
    monto_consulta_particular NUMERIC(10,2) DEFAULT 1500,
    exequatur TEXT,
    email TEXT,
    CONSTRAINT check_single_row CHECK (id = 1)
);
ALTER TABLE configuracion_doctor DISABLE ROW LEVEL SECURITY;

-- 9. TABLA TARIFAS SEGURO
CREATE TABLE IF NOT EXISTS tarifas_seguro (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    seguro TEXT NOT NULL UNIQUE,
    monto_cobertura NUMERIC(10,2) NOT NULL,
    copago NUMERIC(10,2) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE tarifas_seguro DISABLE ROW LEVEL SECURITY;

-- 10. TABLA REPORTES PAGOS SEGURO
CREATE TABLE IF NOT EXISTS reportes_pagos_seguro (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    seguro TEXT NOT NULL,
    fecha_reporte DATE DEFAULT CURRENT_DATE,
    monto_total NUMERIC(15,2) NOT NULL,
    cantidad_facturas INTEGER NOT NULL,
    estado TEXT DEFAULT 'pendiente',
    fecha_pago DATE,
    comprobante_url TEXT,
    facturas_ids BIGINT[],
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE reportes_pagos_seguro DISABLE ROW LEVEL SECURITY;

-- PUBLICACIONES EN TIEMPO REAL (REALTIME)
ALTER PUBLICATION supabase_realtime ADD TABLE citas, pacientes, consultas, transacciones, facturas_seguro, configuracion_doctor, tarifas_seguro, usuarios;

-- BUCKET DE ALMACENAMIENTO PARA AVATARES
INSERT INTO storage.buckets (id, name, public) VALUES ('avatars', 'avatars', true) ON CONFLICT DO NOTHING;

-- POLÍTICAS PÚBLICAS PARA EL BUCKET AVATARS
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE policyname = 'Avatars Public Access' AND tablename = 'objects'
    ) THEN
        CREATE POLICY "Avatars Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'avatars');
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE policyname = 'Avatars Public Upload' AND tablename = 'objects'
    ) THEN
        CREATE POLICY "Avatars Public Upload" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'avatars');
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE policyname = 'Avatars Public Update' AND tablename = 'objects'
    ) THEN
        CREATE POLICY "Avatars Public Update" ON storage.objects FOR UPDATE USING (bucket_id = 'avatars');
    END IF;
END $$;

-- CORRECCIÓN DE COLUMNAS DE IDENTIDAD PARA PERMITIR INSERCIÓN DE DATOS EXISTENTES
ALTER TABLE citas ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE transacciones ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE facturas_seguro ALTER COLUMN id SET GENERATED BY DEFAULT;
